services:
  mariadb:
    image: mariadb:11.4
    container_name: goms-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:7.4
    container_name: goms-redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: goms-app
    restart: always
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "127.0.0.1:8080:8080"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1400"

volumes:
  mariadb_data:
    name: goms-backend-v3_mariadb_data
  redis_data:
    name: goms-backend-v3_redis_data
