spring:
  application:
    name: goms-server-v3

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:goms_v3_db}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:qaqawesd12@}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:false}
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    time-zone: Asia/Seoul

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG:OFF}
    org.hibernate.type.descriptor.sql.BasicBinder: ${HIBERNATE_BIND_LOG:OFF}

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: "c2e9f7a1d4b8k3m6q9w2x5z8n1p4r7t0v3y6u9i2o5p8a1s4d7f0g3h6j9k2l5"
  access-exp-seconds: 1800
  refresh-exp-seconds: 1209600